[tools]
ruby = "3.3"
node = "25"
python = "3.11"
maven = "3.9"
java = "corretto-21"
glab = "1.92"
clickhouse = "26"
"npm:@anthropic-ai/claude-code" = "2"

[settings]
python.github_attestations = false
ruby.github_attestations = false
ruby.compile = false
