[tools]
java = ["graalvm-community-21.0.2", "corretto-8.452.09.1"]
ruby = "3.3"
node = "25"
python = "3.10"
glab = "1.92"
clickhouse = "26"
"npm:@anthropic-ai/claude-code" = "2"

[settings]
python.github_attestations = false
ruby.github_attestations = false
ruby.compile = false
